name: flutter_rename_app_plus3
description: A package that enable to rename an entire app and ids in one command.
version: 1.2.4
homepage: https://github.com/qipengxiang/flutter_rename_app_plus3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  process_run: ^0.13.0
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  plugin:
#    platforms:
#      android: true
#      ios: true